version: '3.8'

services:
  server:
    image: zabbix/zabbix-server-pgsql
    environment:
      DB_SERVER_HOST: db
      DB_SERVER_PORT: 5432
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix

      ZBX_JAVAGATEWAY_ENABLE: true
      ZBX_JAVAGATEWAY: gateway

      ZBX_ENABLE_SNMP_TRAPS: true
    volumes:
      - var-lib-zabbix-export:/var/lib/zabbix/export
      - var-lib-zabbix-snmptraps:/var/lib/zabbix/snmptraps
      - var-lib-zabbix-module:/var/lib/zabbix/module
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - var-lib-postgresql-data:/var/lib/postgresql/data

  gateway:
    image: zabbix/zabbix-java-gateway
    volumes:
      - usr-sbin-zabbix_java-ext_lib:/usr/sbin/zabbix_java/ext_lib

  web:
    image: zabbix/zabbix-web-nginx-pgsql
    environment:
      DB_SERVER_HOST: db
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: server
      PHP_TZ: Asia/Taipei
    ports:
      - 8080:8080
    depends_on:
      - db
      - server
  
  snmp:
    image: zabbix/zabbix-snmptraps
    volumes:
      - var-lib-zabbix-snmptraps:/var/lib/zabbix/snmptraps

  agent:
    image: zabbix/zabbix-agent
    privileged: true
    environment:
      ZBX_HOSTNAME: agent
      ZBX_SERVER_HOST: server
    volumes:
      - var-lib-zabbix-module:/var/lib/zabbix/module

  proxy:
    image: zabbix/zabbix-proxy-sqlite3
    profiles:
      - all
    environment:
      ZBX_SERVER_HOST: server
      ZBX_JAVAGATEWAY_ENABLE: true
    volumes:
      - var-lib-zabbix-snmptraps:/var/lib/zabbix/snmptraps
      - var-lib-zabbix-module:/var/lib/zabbix/module
    depends_on:
      - gateway
      - snmp


volumes:
  var-lib-postgresql-data:
  usr-sbin-zabbix_java-ext_lib:
  var-lib-zabbix-snmptraps:
  var-lib-zabbix-module:
  var-lib-zabbix-export:
